[package]
name = "boids"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6"
glam = "0.17"
rand = "0.8"
ghost-cell = "0.2"
typed-arena = "2"
